// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gssbpttummndnwmhvwzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzc2JwdHR1bW1uZG53bWh2d3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjI1NzMsImV4cCI6MjA1OTc5ODU3M30.n-LeITj1FJB_vQBg2dBQYUWaqLUQk5yVTFZ1tcxt7Ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);